보안 취약점 개선
wafflestudio/wafflestudio.com pull request #72
Opened 2022-11-24 06:58 UTC by minkyu97

## 변경 사항
하기 패키지 업데이트
- minimist 1.2.5 -> 1.2.6
- shell-quote 1.7.2 -> 1.7.3
- loader-utils 2.0.0 -> 2.0.3

## 관련 이슈
https://wafflestudio.slack.com/archives/C02T5M5DVRP/p1669043185926549
https://github.com/wafflestudio/wafflestudio.com/security/dependabot/27
https://github.com/wafflestudio/wafflestudio.com/security/dependabot/30
https://github.com/wafflestudio/wafflestudio.com/security/dependabot/32
https://github.com/wafflestudio/wafflestudio.com/security/dependabot/39

## 체크리스트
- [x] 동작 확인
- [x] 코드 포맷팅

2022-11-24 07:05 UTC, joongwon approved these changes

2022-11-24 07:16 UTC, woohm402 requested changes
엇 이게 아닐 것 같은데 [슬랙](https://wafflestudio.slack.com/archives/C01KGJSRPRC/p1669273322732209)에서 논의 가능할까요? (제가 코드 오너는 아니지만..)

2022-11-25 03:39 UTC, minkyu97 commented on package.json
> +    "**/minimist": "^1.2.6"
`resolutions` 항목을 추가해서 문제가 있는 패키지들을 필요로 하는 경우에도 일정 이상의 버전을 설치하도록 강제했습니다.

2022-11-25 03:48 UTC, woohm402 commented on package.json
> +    "**/minimist": "^1.2.6"
이렇게 되면 `styled-jsx` 는 `1.2.3` 에 의존해야 되는데 강제로 `2.0.4` 에 의존하게 되어 breaking change 를 만나니까 없던 버그가 생길 수 있지 않으려나요..?

2022-11-25 03:51 UTC, woohm402 commented on package.json
> +    "**/minimist": "^1.2.6"
해당 [도큐먼트](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-why-would-you-want-to-do-this)에도 나와있지만.. 지금 상황에 쓰기 적절한 기능은 아닌 것 같다는 생각이 계속 들긴 합니다 😭 물론 제가 코드 메인테이너는 아니지만 소소한 의견 드려요

2022-11-25 04:18 UTC, minkyu97 commented on yarn.lock
> -
그리고 안 쓰는 패키지인 `raw-loader`도 삭제했습니다.
next, next-images도 최신화 하려고 했는데 단순히 패키지 업데이트만 하면 되는 게 아니라 이것저것 고칠 게 많아서 그냥 냅뒀습니다 ㅜ

2022-11-25 04:20 UTC, minkyu97 commented on package.json
> +    "**/minimist": "^1.2.6"
그렇군요.. 그러면 현재로서는 모든 패키지를 최신화하지 않는 이상 안 하느니만 못한 것인가요?

2022-11-25 04:52 UTC, woohm402 commented on package.json
> +    "**/minimist": "^1.2.6"
저것들이 해결된 버전으로 next 등의 패치버전을 올리는 게 제대로 된 해결방법일 것 같습니다 (최신버전으로 올리는 건 공수가 크게 들어가니까)

2022-11-26 11:17 UTC, minkyu97 commented
sry!... orz...

2022-11-26 11:17 UTC, closed without merging